REVOKE ALL ON SCHEMA catalog FROM catalog_manager;
REVOKE ALL ON ALL TABLES IN SCHEMA catalog FROM catalog_manager;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA catalog FROM catalog_manager;
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog REVOKE ALL ON TABLES FROM catalog_manager;
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog REVOKE ALL ON SEQUENCES FROM catalog_manager;

REVOKE ALL ON SCHEMA sales FROM sales_manager;
REVOKE ALL ON ALL TABLES IN SCHEMA sales FROM sales_manager;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA sales FROM sales_manager;
ALTER DEFAULT PRIVILEGES IN SCHEMA sales REVOKE ALL ON TABLES FROM sales_manager;
ALTER DEFAULT PRIVILEGES IN SCHEMA sales REVOKE ALL ON SEQUENCES FROM sales_manager;

REVOKE USAGE ON SCHEMA catalog FROM PUBLIC;
REVOKE SELECT ON ALL TABLES IN SCHEMA catalog FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog REVOKE SELECT ON TABLES FROM PUBLIC;

ALTER TABLE sales.orders DROP CONSTRAINT IF EXISTS fk_orders_created_by;
ALTER TABLE sales.orders DROP COLUMN IF EXISTS created_by;